config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'shopping/generate_shopping_list',to: 'shopping#generate_shopping_list', as: 'generate_shopping_list'
  resources :food_recipes, only: [:new, :create, :destroy]
  resources :food_inventories, only: [:new, :create, :destroy]
  resources :public_recipes, only: [:index]
  resources :inventories, except: [:edit, :update]
  resources :recipes, except: %i[edit]
  devise_for :users
  root 'home#index'
  get '/foods', to: 'foods#index'
  get '/foods/new', to: 'foods#new', as: 'new_food'
  resources :foods, only: [:create,:destroy]
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user

  has_many :food_inventories
  has_many :foods, through: :food_inventories

  validates :name, presence: true
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[show destroy]

  # GET /inventories or /inventories.json
  def index
    @inventories = Inventory.where(user_id: current_user.id)
  end

  # GET /inventories/1 or /inventories/1.json
  def show
    @food_inventories = FoodInventory.includes(:food).where(inventory_id: params[:id])
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # POST /inventories or /inventories.json
  def create
    @inventory = Inventory.new(inventory_params.merge(user: current_user))

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventories_url, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    @inventory.destroy!

    if @inventory.destroy
      flash[:notice] = 'Food removed successfully.'
      redirect_to inventories_path
    else
      flash[:alert] = 'Failed to remove food.'
      redirect_back(fallback_location: inventories_path)
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_inventory
    @inventory = Inventory.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<div style="max-width: 35vw; margin: 0 auto;" class="mx-auto mb-4 p-3 bg-light border rounded">
  <%= form_with(model: inventory) do |form| %>
    <% if inventory.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

        <ul>
          <% inventory.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control fixed-height-textarea" %>
    </div>

    <div class="mb-3 text-center">
      <%= form.submit class: "btn btn-primary w-100" %>
    </div>
  <% end %>
</div>

app/views/inventories/_inventory.html.erb
<div id="<%= dom_id inventory %>" class="d-flex inventory-item border rounded p-3 mb-3">
    <div class="d-flex flex-column justify-content-between col-md-2">
      <h3 class="mb-5 text-center">
        <strong><%= inventory.name %></strong>
      </h3>
      <%if action_name == 'index' && can?(:destroy, inventory) %>
        <%= link_to "Remove", inventory_path(inventory.id), data: { confirm: 'Are you sure?', turbo_method: :delete }, class: "btn btn-danger" %>
      <% end %>
    </div>
    <p class="p-1 px-5 m-0"><%= inventory.description %></p>
</div>

app/views/inventories/index.html.erb
<div>
  <strong><%= link_to "New inventory", new_inventory_path, class: "btn btn-primary mb-4" %></strong>

  <div id="inventories">
    <% if @inventories.any? %>
      <% current_user.inventories.each do |inventory| %>
        <%= link_to inventory_path(inventory.id) do %>
          <%= render inventory %>
        <% end %>
      <% end %>
    <% else %>
      <div class="text-center py-3 bg-light border rounded">
        <p class="text-muted mb-0">Empty list for now</p>
      </div>
    <% end %>
  </div>
</div>

app/views/inventories/new.html.erb
<h1 class="text-center mb-5">New inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Back to inventories", inventories_path, class: "btn btn-outline-danger rounded-5 px-4" %>
</div>

app/views/inventories/show.html.erb
<div class="inventory-item-header">
    <div class="inventory-header-show d-flex flex-column justify-content-between align-items-center">
      <strong> <h3> <%= @inventory.name %> </h3> </strong>
      <%= link_to "Add ingredient", new_food_inventory_path(inventory_id: @inventory.id), class: "btn btn-outline-success add-ingredient-show add-ingredient-btn" %>
      <%if action_name == 'index' && can?(:destroy, @inventory) %>
        <%= link_to "Remove", inventory_path(@inventory.id), data: { confirm: 'Are you sure?', turbo_method: :delete }, class: "btn btn-danger" %>
      <% end %>
    </div>
    <% if action_name == 'index' %>
      <p class="Inventory-description">
        <%= @inventory.description ? @inventory.description : 'No description available' %>
      </p>
    <% end %>
  </div>

  <hr>
  
  <table class="table table-striped table-bordered">
    <thead class="inventories-table-header">
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
    </thead>
    <% if @food_inventories.any? %>
      <tbody>
      <% @food_inventories.each do |food_inventory| %>
        <tr>
          <td class="align-middle"><%= food_inventory.food.name %></td>
          <td class="align-middle"><%= food_inventory.quantity_with_measurement %></td>
          <td class="align-middle">
            <%= link_to "Remove", food_inventory_path(food_inventory.id), class: "btn btn-outline-danger rounded-5 px-4", data: { turbo_method: :delete } %>
          </td>
        </tr>
        <% end %>
      </tbody>
      <% else %>
        <tr>
          <td colspan="3">Empty list for now</td>
        </tr>
      <% end %>
  </table>

<div>
  <%= link_to "Back to inventories", inventories_path, class: "btn btn-outline-danger rounded-5 px-4" %>
</div>