config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'shopping/generate_shopping_list',to: 'shopping#generate_shopping_list', as: 'generate_shopping_list'
  resources :food_recipes, only: [:new, :create, :destroy]
  resources :food_inventories, only: [:new, :create, :destroy]
  resources :public_recipes, only: [:index]
  resources :inventories, except: [:edit, :update]
  resources :recipes, except: %i[edit]
  devise_for :users
  root 'home#index'
  get '/foods', to: 'foods#index'
  get '/foods/new', to: 'foods#new', as: 'new_food'
  resources :foods, only: [:create,:destroy]
end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController
  # ...

  def generate_shopping_list
    inventory_id = params[:user_id]
    recipe_id = params[:recipe_id]
    @inventory = Inventory.find(inventory_id)
    @recipe = Recipe.find_by(id: recipe_id)

    @food_inventory = @inventory.foods
    @food_recipe = @recipe.foods

    # Find the missing foods
    @missing_foods = @food_recipe - @food_inventory

    # Calculate the total quantity and total price
    @total_quantity = @missing_foods.size
    @total_price = @missing_foods.sum { |food| food.price * @recipe.food_quantity(food) }

    render 'generate_shopping_list'
  end
end

app/helpers/shopping_helper.rb
module ShoppingHelper
end

app/views/shopping/generate_shopping_list.html.erb
<!-- Previous content remains unchanged -->

<div class="row mt-3">
<div class="col-md-6">
<p>Total Kinds of Foods to Buy: <%= @total_quantity %></p>
<p>Total Money to Spend: <%= number_to_currency(@total_price) %></p>
</div>
  <div class="col-md-6">
    <p><strong>Recipe:</strong> <%= link_to @recipe.name, recipe_path(@recipe) %></p>
    <p><strong>Inventory:</strong> <%= link_to @inventory.name, inventory_path(@inventory) %></p>
  </div>
</div>

<div class="row mt-4">
  <div class="col-md-12">
    <h2>Missing Foods:</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Amount to Buy</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @missing_foods.each do |missing_food| %>
          <tr>
            <td><%= missing_food.name %></td>
            <td><%= @recipe.food_quantity(missing_food) %></td>
            <td>$<%= (missing_food.price)*( @recipe.food_quantity(missing_food)) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>