config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'shopping/generate_shopping_list',to: 'shopping#generate_shopping_list', as: 'generate_shopping_list'
  resources :food_recipes, only: [:new, :create, :destroy]
  resources :food_inventories, only: [:new, :create, :destroy]
  resources :public_recipes, only: [:index]
  resources :inventories, except: [:edit, :update]
  resources :recipes, except: %i[edit]
  devise_for :users
  root 'home#index'
  get '/foods', to: 'foods#index'
  get '/foods/new', to: 'foods#new', as: 'new_food'
  resources :foods, only: [:create,:destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :food_recipes
  has_many :foods, through: :food_recipes

  validates :name, presence: true
  def total_price
    total = 0
    food_recipes.each do |rf|
      total += rf.food.price
    end
    total
  end

  def food_quantity(food)
    food_recipes.find_by(food:).quantity
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show update destroy]
  before_action :authenticate_user!

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @food_recipes = FoodRecipe.includes(:food, :recipe).where(recipe_id: params[:id])
    @inventories = Recipe.where(user_id: current_user.id)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    user = current_user
    @recipe = Recipe.new(recipe_params)
    @recipe.user = user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update_attribute(:public, !@recipe.public)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { redirect_to recipe_url(@recipe), alert: 'Recipe was not updated.' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.food_recipes.destroy_all
    @recipe.destroy

     if @recipe.destroy
      flash[:notice] = 'Food removed successfully.'
      redirect_to recipes_path
    else
      flash[:alert] = 'Failed to remove food.'
      redirect_back(fallback_location: recipes_path)
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="px-2 m-auto" style="max-width: 450px;">
  <div class="shadow rounded px-3 py-3">
    <%= form_with(model: recipe) do |form| %>
      <% if recipe.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

          <ul>
            <% recipe.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group mb-3">
        <%= form.label :name, :class => "mb-2" %>
        <%= form.text_field :name, placeholder: 'Example: Chicken curry', :class => "form-control" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :preparation_time, :class => "mb-2" %>
        <%= form.text_field :preparation_time, placeholder: 'Example: 1hr 30mins', :class => "form-control" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :cooking_time, :class => "mb-2" %>
        <%= form.text_field :cooking_time, placeholder: 'Example: 1hr 30mins', :class => "form-control" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :description, :class => "mb-2" %>
        <%= form.text_area :description, placeholder: 'Enter your description here', :class => "form-control" %>
      </div>

      <div class="form-check mb-3">
        <%= form.label :public %>
        <%= form.check_box :public, :class => "form-check-input" %>
      </div>

      <div class="form-group mb-3">
        <%= form.submit 'Save', :class => "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/_modal.html.erb
<div class="modal fade" id="genIngredient" tabindex="-1" role="dialog" aria-labelledby="genIngredientTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Generate Shopping List</h5>
        <button type="button" class="btn-close" id="head-close-modal" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"></span>
        </button>
      </div>
      <div class="modal-body">
        <h5>Choose an inventory to use</h5>
          <!-- Replace recipe_path with the shopping list path you create -->
          <%= form_tag(generate_shopping_list_path, method: :get) do %>
 <%= hidden_field_tag :recipe_id, @recipe.id %>
  <%= select_tag 'user_id', options_for_select(@inventories.collect { |i| [i.name, i.id] }), { prompt: "Select an Inventory" } %>
  <%= submit_tag 'Generate' %>
<% end %>

      </div>
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <h1 class="text-secondary text-center mb-4">
    <%= recipe.name %>
  </h1>

  <div class="row my-3">
    <div class="col-sm-12 col-md-8 col-lg-8">
      <p>
        <span style="font-weight: bold;">Preparation time:</span>
        <%= recipe.preparation_time %>
      </p>
      <p>
        <span style="font-weight: bold;">Cooking time:</span>
        <%= recipe.cooking_time %>
      </p>
      <p>
        <span style="font-weight: bold;">Description</span>
        <p><%= recipe.description %></p>
      </p>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4">
      <% if can? :update, recipe %>
        <%= link_to recipe_path(recipe), method: :patch do %>
          <div class="form-check form-switch">
            <label class="form-check-label" for="flexSwitchCheckDefault">Public</label>
            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" <%= recipe.public ? 'checked' : '' %>>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-8">
      <button type="button" id="generate-ingredient" class="btn btn-primary">Generate Shopping List</button>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4">
      <% if can? :create_food, recipe %>
        <%= link_to 'Add Ingredient', new_food_recipe_path(recipe_id: recipe.id), class: 'btn btn-secondary' %>
      <% end %>
    </div>
  </div>

  

  <%= render 'table' %>

  <%= render 'modal' %>

</div>

app/views/recipes/_recipeindex.html.erb
<div id="<%= dom_id recipe %>" class='shadow mx-3 row p-3 mb-4'>
  <div class="col-sm-12 col-md-4 col-lg-4">
    <%= link_to recipe_path(recipe) do %>
      <h5 class="text-dark mb-5">
        <%= recipe.name %>
      </h5>
    <% end %>
    <% if can? :destroy, recipe %>
      <%= button_to "Remove", recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure you want to delete this recipe ?' }, class: 'btn btn-danger' %>
    <% end %>
  </div>

  <div class="col-sm-12 col-md-8 col-lg-6">
    <p class='text-secondary'>
      <%= recipe.description %>
    </p>
  </div>

</div>

app/views/recipes/_table.html.erb
<table class="table table-striped my-3">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @food_recipes.each_with_index do |food_recipe, index| %>
      <tr>
        <th scope="row"><%= index %></th>
        <td><%= food_recipe.food.name %></td>
        <td><%= food_recipe.quantity_with_measurement_unit %></td>
        <td>$<%= food_recipe.quantity * food_recipe.food.price %></td>
        <td class="d-flex align-items-center" >
          <% if can? :update, food_recipe %>
            <button type="button" class="btn btn-primary mx-1">Modify</button>
          <% end %>
          <% if can? :destroy, food_recipe %>
            <%= button_to "Remove", food_recipe_path(food_recipe), method: :delete, data: { confirm: 'Are you sure you want to delete this recipe food ?' }, class: 'btn btn-danger mx-1' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/index.html.erb
<h1 class="text-center text-secondary mb-4">Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render partial: 'recipeindex', locals: { recipe: recipe } %>
  <% end %>
</div>

<div class="d-flex align-items-center justify-content-center">
  <%= link_to "New recipe", new_recipe_path, :class => "btn btn-outline-danger rounded-5 px-4 my-3" %>
</div>

app/views/recipes/new.html.erb
<h1 class="text-center text-secondary mb-4">New Recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div class="d-flex align-items-center justify-content-center">
  <%= link_to "Back to recipes", recipes_path, :class => "btn btn-outline-danger rounded-5 px-4 my-3" %>
</div>

app/views/recipes/show.html.erb
<% if can? :read, @recipe %>
  <%= render @recipe %>
<% else %>
  <p class="text-center text-danger my-4">Sorry! You do not have the permission to view this recipe.</p>
<% end %>

<div class="d-flex align-items-center justify-content-center">
  <%= link_to "Back to Recipes", recipes_path, :class => "btn btn-outline-danger rounded-5 px-4 my-3" %>
</div>