config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'shopping/generate_shopping_list',to: 'shopping#generate_shopping_list', as: 'generate_shopping_list'
  resources :food_recipes, only: [:new, :create, :destroy]
  resources :food_inventories, only: [:new, :create, :destroy]
  resources :public_recipes, only: [:index]
  resources :inventories, except: [:edit, :update]
  resources :recipes, except: %i[edit]
  devise_for :users
  root 'home#index'
  get '/foods', to: 'foods#index'
  get '/foods/new', to: 'foods#new', as: 'new_food'
  resources :foods, only: [:create,:destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    return unless user.persisted?

    can :create, [Inventory]
    can :read, [Inventory]
    can :destroy, [Inventory], user_id: user.id

    can :update, Recipe, user_id: user.id
    can :destroy, Recipe, user_id: user.id
    can :read, Recipe do |recipe|
      user.id == recipe.user_id || recipe.public?
    end

    can :update, FoodRecipe do |food_recipe|
      food_recipe.recipe.user_id == user.id
    end
    can :destroy, FoodRecipe do |food_recipe|
      food_recipe.recipe.user_id == user.id
    end

    can :create_food, Recipe, user_id: user.id

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :food_recipes, dependent: :destroy
  has_many :recipes, through: :food_recipes

  def total_price
    total = 0
    food_recipes.each do |rf|
      total += rf.food.price
    end
    total
  end
end

app/models/food_inventory.rb
class FoodInventory < ApplicationRecord
  belongs_to :inventory
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :inventory_id, presence: true
  validates :food_id, presence: true

  def quantity_with_measurement
    "#{quantity} #{food.measurement_unit}"
  end
end

app/models/food_recipe.rb
class FoodRecipe < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

   def quantity_with_measurement_unit
    "#{quantity} (#{food.measurement_unit})"
  end
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user

  has_many :food_inventories
  has_many :foods, through: :food_inventories

  validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :food_recipes
  has_many :foods, through: :food_recipes

  validates :name, presence: true
  def total_price
    total = 0
    food_recipes.each do |rf|
      total += rf.food.price
    end
    total
  end

  def food_quantity(food)
    food_recipes.find_by(food:).quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :foods
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :inventories
  has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create destroy]
  before_action :food_by_user, only: %i[index new create destroy]

  def index
    @foods = current_user.foods.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id # Set the user_id to the ID of the current user

    if @food.save
      flash[:notice] = 'The Food was created successfully!'
      redirect_to foods_path
    else
      render :new
    end
  end

  def destroy
    @food = current_user.foods.find(params[:id])
    if @food.destroy
      flash[:notice] = 'The Food was deleted successfully!'
    else
      flash[:alert] = 'The Food was not deleted!'
    end
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end

  def food_by_user
    @food = current_user.foods
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # come code can go here
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show update destroy]
  before_action :authenticate_user!

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @food_recipes = FoodRecipe.includes(:food, :recipe).where(recipe_id: params[:id])
    @inventories = Recipe.where(user_id: current_user.id)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    user = current_user
    @recipe = Recipe.new(recipe_params)
    @recipe.user = user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update_attribute(:public, !@recipe.public)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { redirect_to recipe_url(@recipe), alert: 'Recipe was not updated.' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.food_recipes.destroy_all
    @recipe.destroy

     if @recipe.destroy
      flash[:notice] = 'Food removed successfully.'
      redirect_to recipes_path
    else
      flash[:alert] = 'Failed to remove food.'
      redirect_back(fallback_location: recipes_path)
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController
  # ...

  def generate_shopping_list
    inventory_id = params[:user_id]
    recipe_id = params[:recipe_id]
    @inventory = Inventory.find(inventory_id)
    @recipe = Recipe.find_by(id: recipe_id)

    @food_inventory = @inventory.foods
    @food_recipe = @recipe.foods

    # Find the missing foods
    @missing_foods = @food_recipe - @food_inventory

    # Calculate the total quantity and total price
    @total_quantity = @missing_foods.size
    @total_price = @missing_foods.sum { |food| food.price * @recipe.food_quantity(food) }

    render 'generate_shopping_list'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_inventories_helper.rb
module FoodInventoriesHelper
end

app/helpers/food_recipes_helper.rb
module FoodRecipesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_helper.rb
module ShoppingHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-secondary rounded mb-3 ">
  <div class="container-fluid " >
    <%= link_to 'Home', recipes_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Public Recipes', public_recipes_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'All invetories', inventories_path, class: 'nav-link' %>
        </li>
         <li class="nav-item">
           <%= link_to 'Add food', new_food_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Foods', foods_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'New Recipe', new_recipe_path, class: 'nav-link' %>
        </li>
         <li class="nav-item">
          <%= link_to 'All Recipes', recipes_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>

    <div class="text-end">
      <%= form_tag destroy_user_session_path, method: :delete do %>
        <%= submit_tag "Log Out #{current_user.email.split("@").first.gsub(/[^a-zA-Z]/, '')}", class: "btn btn-outline-danger" %>
      <% end %>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deviselearning</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'rails-ujs', 'data-turbo-frame': 'false' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'register_new' %>
     <%= stylesheet_link_tag 'session_new' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <div class="container my-4" >
      <div class="mb-3">
       <% if user_signed_in? %>
         <%= render 'layouts/nav' %>
        <% end %>
    </div>
    <p style="color: green" class="notice"><%= notice %></p>
    <p style="color: red" class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/partials/_table_food_item.html.erb
<tr>
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td><%= food.price %></td>
  <td>
    <%= button_to 'Delete', food_path(food), method: :delete, data: { confirm: 'Are you sure you want to delete this food?' }, class: 'btn btn-outline-danger rounded-5 px-4' %>
  </td>
</tr>